# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 14:14
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': '文章撰写', 'verbose_name_plural': '文章撰写'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=32, verbose_name='文章作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='文章标题'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
