# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170516_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='short_name',
            field=models.CharField(default='', max_length=255, verbose_name='地址显示'),
        ),
    ]
