# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170518_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleApproved',
            fields=[
            ],
            options={
                'verbose_name': '已审核文章',
                'verbose_name_plural': '已审核文章',
                'proxy': True,
            },
            bases=('app.article',),
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
            ],
            options={
                'verbose_name': '文章审核',
                'verbose_name_plural': '文章审核',
                'proxy': True,
            },
            bases=('app.article',),
        ),
        migrations.AddField(
            model_name='article',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='是否审核通过'),
        ),
    ]
