"""empty message

Revision ID: 583b4ed3da2
Revises: 22726747cd8e
Create Date: 2016-08-10 14:08:01.655735

"""

# revision identifiers, used by Alembic.
revision = '583b4ed3da2'
down_revision = '22726747cd8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
